# easy_admin.yaml
easy_admin:
    entities:
        Category:
            class: App\Entity\Category
            fields:
                - property: 'products'
                  type: 'association'
                  type_options:
                      class: 'App\Entity\Product'
                      multiple: true
                      autocomplete: true
        Product:
            class: App\Entity\Product
            fields:
                - property: 'categories'
                  type: 'association'
                  type_options:
                      class: 'App\Entity\Category'
                      multiple: true
                      autocomplete: true
